### ISSUE TITLE
WTB: clone && cd

### ISSUE THREAD

**Issue by listrophy** [bendyworks/buffet#14]
Want to buy something that does this (probably a git-command):

    $ git clone git://example.com/user/foo.git && cd foo

**Comment by listrophy** [comment]
This works, but you lose out on the extra info that git-clone provides while it's doing its thing, like `remote: Counting objects: 279, done.`

```
gtake() {
  local tmp=$(mktemp git-output)
  local repo_name

  git clone "$@" 2>&1 | tee $tmp
  repo_name=$(awk -F\' '/Cloning into/ {print $2}' $tmp)
  rm $tmp
  cd "$repo_name"
}
```

**Comment by Jonplussed** [comment]
All that just to avoid `cd`? Seems a biiiiiit excessive.
