### ISSUE TITLE
Installing for the first time puts lots of errors into console

### ISSUE THREAD

**Issue by schbetsy** [bendyworks/buffet#19]
After running the deploy script for the first time, whenever I open a new terminal session, I get hundreds of errors.
Many look like this: 
```
bash: have: command not found
```

Some are syntax errors in specific files. It appears they're all in files in `/usr/local/etc/bash_completion.d/`, e.g.:
```
bash: /usr/local/etc/bash_completion.d/aptitude: line 32: syntax error in conditional expression: unexpected token `('
```

The files in that directory that are getting syntax errors seem to be symlinked to `/usr/local/Cellar/bash-completion/1.3/etc/bash_completion.d/`, so they may be brew related?

**Comment by twopoint718** [comment]
The only thing I see is that buffet sources all the bash completions that it can find:
https://github.com/bendyworks/buffet/blob/master/dotfiles/bashrc#L76-L82
This is the proximate cause of the errors, but I'm not seeing what else may be happening to cause these. Are homebrew's bash completions just really buggy?

**Comment by twopoint718** [comment]
@schbetsy, looks like @wstrinz got this one. Thanks!
