### ISSUE TITLE
Tab autocomplete breaks on git branch -d

### ISSUE THREAD

**Issue by kliph** [bendyworks/buffet#34]
To reproduce, type `git branch -d [TAB]` in a repo with branches.

**Comment by wstrinz** [comment]
I've seen this too :frowning: 

 Guessing it's got something to do with the weird hack for multiple line output. Hopefully I'll have time to tackle it soon

**Comment by wstrinz** [comment]
Finally found the source of this! :confetti_ball: 

https://github.com/bendyworks/buffet/blob/master/dotfiles/prompt#L66 overrides git autocomplete's internal function for git branch, which, coincidentally, is *also* called `_git_branch` . working on a fix this afternoon
