### ISSUE TITLE
Error messages while in bare Git repos

### ISSUE THREAD

**Issue by SaxxonPike** [bendyworks/buffet#36]
When working with bare Git repositories, there's a script that keeps attempting to run a command that is not successful while in a folder that contains a bare Git repo. I'm not really sure which one it is. 

Here's how you can reproduce:
```
mkdir bears.git
cd bears.git
git init --bare
```

Immediately after executing `git init --bare`, each command attempted while in the repo will show `fatal: This operation must be run in a work tree`. This happens in Debian 8, though I suspect it may happen on other distributions.

**Comment by wstrinz** [comment]
thanks for the report! reproduced on OS X, taking a look at it now
