### ISSUE TITLE
Autocompletion fails on aliases

### ISSUE THREAD

**Issue by Jonplussed** [bendyworks/buffet#4]
Example: [homebrew][1] installs autocompletion files for git, which is aliased in `.bashrc` to `g`. Autocompletion of git arguments succeeds when typing `git` in the terminal, but fails when using the alias `g`.

Here's one [possible solution][2].

[1]: http://brew.sh
[2]: http://unix.stackexchange.com/questions/75956/tab-completion-doesnt-work-for-arguments-when-command-is-an-alias

**Comment by schbetsy** [comment]
I solved this issue in my dotfiles with [this commit](https://github.com/schbetsy/dotfiles/commit/fd9ca9d9191125b8255088ed65511290c6b16a38). I borrowed the solution from StackOverflow, but I don't remember where.

Basically, I added this line to my `.bashrc`:
```
__git_complete g __git_main
```

**Comment by Jonplussed** [comment]
@schbetsy :+1: awesooooooome
