### ISSUE TITLE
Add Atom support

### ISSUE THREAD

**Issue by wstrinz** [bendyworks/buffet#43]
Many bendyworkers use atom as a default; buffet should definitely install some common extensions with `apm`

**Proposed Packages** (please suggest or bikeshed)
- [linter](https://atom.io/packages/linter)
- [merge-conflicts](https://atom.io/packages/merge-conflicts)
- [markdown-folder](https://atom.io/packages/markdown-folder)
- [script](https://atom.io/packages/script)
- [vim mode](https://atom.io/packages/vim-mode)
- [vim surround](https://atom.io/packages/vim-surround)
- [atom pair](https://atom.io/packages/atom-pair)

**Comment by kliph** [comment]
This might require that users have installed the Atom CLI stuff.  Not sure.  Maybe @abraham knows more.

**Comment by wstrinz** [comment]
Ya, installing `apm` might be something buffet can do as well

**Comment by abraham** [comment]
Maybe have a list of atom packages and at some point (not sure when) they get installed/updated?

**Comment by wstrinz** [comment]
Good point, going to add a WIP list to the top of this issue for RFCing

**Comment by wstrinz** [comment]
Closing this since we're installing APM packages during setup.
