### ISSUE TITLE
Add a default emacs config

### ISSUE THREAD

**Issue by wstrinz** [bendyworks/buffet#44]
I know, I know, we're a vim shop. But with people using Atom ( #43 ), perhaps we should have an emacs as well? Even some people who aren't @kliph like Org mode!

[This is mine at the moment](https://gist.github.com/wstrinz/52bb769846e15c1cc18428272b068a46). It's had modifications from too many bendyworkers to be viable though.

Perhaps someone (such as @kliph 😉 😉 ) wants to czar this?

**Comment by kliph** [comment]
Here's the basis of a barebones setup I was using on `roci`: [.emacs](https://gist.github.com/kliph/7e325ed7d0f94f8415ab0acddc3971c9)

**Comment by kliph** [comment]
It would be good to try to collate both of these.  Maybe over a lunch or on a growthday.

**Comment by kliph** [comment]
I'm really like `company-mode` for completion.  Let's use that too.

**Comment by wstrinz** [comment]
👍 plz to PR this `.emacs`

**Comment by vburzynski** [comment]
Closing this as:
- no active users of emacs
- this is old
- #50 was merged in without this being closed
