### ISSUE TITLE
Set default theme

### ISSUE THREAD

**Issue by wstrinz** [bendyworks/buffet#46]
That looks super sweet

Solarized Dark / Monokai Dark / Cyberpunk are some suggestsions

**Comment by abraham** [comment]
I use One Dark for Atom and Terminal so they have a pretty consistent look.

 - https://github.com/nathanbuchar/atom-one-dark-terminal
 - https://atom.io/themes/one-dark-ui
 - https://atom.io/themes/one-dark-syntax

**Comment by wstrinz** [comment]
hrm good point; I made this with Emacs in mind, but we should set a default for other editors too if we're adding support.

Personally recommend [sexy-railscasts](https://github.com/oguzbilgic/sexy-railscasts-theme) for vim
